name = "pallet3d"
main = "worker.js"
compatibility_date = "2024-09-23"

routes = [
  { pattern = "pallet3d.com", custom_domain = true },
  { pattern = "www.pallet3d.com", custom_domain = true }
]

[[send_email]]
name = "EMAIL"
allowed_destination_addresses = ["thekosiner@gmail.com"]

[[d1_databases]]
binding = "DB"
database_name = "pallet3d-db"
database_id = "a94623f1-f288-4dac-88f6-90a47f3443c9"

[vars]
APP_URL    = "https://pallet3d.com"
TRIAL_DAYS = "14"

[assets]
directory = "."
